const MiniCssExtractPlugin = require('mini-css-extract-plugin');

module.exports = {
  // ... existing config
  module: {
    rules: [
      {
        test: /\.css$/i,
        use: [MiniCssExtractPlugin.loader, 'css-loader'],
      },
    ],
  },
  plugins: [new MiniCssExtractPlugin()],
};
